services:
  redis:
    image: "redis:6.2"
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #ports:
    #  - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: "redis"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "poetry run app/manage.py migrate && poetry run app/manage.py runserver 0.0.0.0:8000"
      
volumes:
  postgres_data:
