# Generated by Django 5.1.6 on 2025-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
